### ISSUE TITLE
Looks at editorial/figure comments from Julie Marentette and Andy

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#117]
See email from Julie and Melissa
Andy says he will send us some comments

**Comment by andrew-edwards** [comment]
Awesome job everyone. Having the document so polished made it easier to read
through than usual. These are all very minor and editorial (except one marked * in the Appendix that's a clarification, but even then it's small). These are based on the revised WP
submitted for the meeting. Great job eagain.

Abstract:
- [ ] No need to define acronyms that aren't used again in the
  abstract (adds clutter, and I think CSAS will get you to remove them anyway):
  TACs, ITQs, MSE. 
- [  ] Also DFO is 'Fisheries and Oceans Canada' (someone else noted
  that), and should be in first paragraph.
- [ ] Paragraph 4 - are the probabilities for 'each and every year'? You had that
clear phrasing later somewhere (e.g. p7).

Main text:
- [ ] page 4, last para: fix @gplot reference, also mention that it's a package
(not the actual synopsis)?
- [ ] p7, last para, 'such aboriginal' to 'such as aboriginal'.
- [ ] p9, para 1, define AIC
- [ ] p12, para3, missing .
- [ ] p13, eqn - technically you might want to use I(Bt > 0.4 Bmsy) where I(.)
is the indicator function (0 if the condition is satisifed, 1 if not). But up to
you - it is kind of explained in the text anyway.
- [ ] p15, para 3 'replicate Best' missing .
- [ ] p15, para 3 remove 'as in', or do ref as ICES (2016)
- [ ] p16, para-3 (3 from bottome): another chance to ask CSAS to have
electronic appendices for code. I think I've asked in the past....
- [ ] p23-24 - no edits, but yes! I kept trying to make this point at the
interim-year assessment meeting but wasn't sure people got it. Very easy to have
conditions that will unnecessarily trigger interim assessments. People weren't
keen on closed-loop simulation either. Thank you!
- [ ] p29 I wonder if it's easy to put a gap between the two left-hand
panels in these sorts of plots. For example Figure 10 it looks like the red and
green lines join up.
- [ ] p30 Any reason this is 95% when the previous was 90%. Worth being
consistent (don't worry too much though)?
- [ ] p31 Caption: It's F/Fmsy v B/Bmsy. Maybe add 'for a single MP' end of
first sentence.
- [ ] p35 para 4, line 3, missing .

**Comment by andrew-edwards** [comment]
Appendix A
- [ ] p41, para 3 last line - should t_{c+1} be t_c + 1? Maybe also elsewhere
(e.g. end of point 3).
- [ ] p41, 1. - seem to have 6 lines within (...).
- [ ] p41, line -1: do you use "D" anywhere else? If not then no need here.
- [ ] p42, I was wondering by here if it's worth having a table of parameter
definitions. You do have Table A.1, but it doesn't have everything. Maybe at
least just mention the table here, and that it contains 'major' (?) definitions.
- [ ] p42, (A.1) L_a needs defining here (not next line), and a is age.
- [ ] p42, (A.2) ....where alpha_W and beta_W are species-specific length-weight coefficients.
- [ ] p42, line before (A.3) - m -> m_l
- [ ] p42, (A.3) the exp(- ln 19...) term could be simplified to just
```\frac{\theta_{l50 - 95}}{19(l - \theta_{l50})}```, then simplify the full
fraction further (avoid the double fraction), but I'm thinking the way it is
more clearly indicates where it's coming from? Also maybe explain the 19 factor?
- [ ] p43, **Clarification** (A.7) Please clarify that (I think) N_{y,a} is the numbers at age a at
the *beginning* of year y. Also (A.8) for biomass. I'm pretty sure everything is
calculated at the start of years, because of the fishing component in (A.13). [I
got a bit confused because (A.7) differs slightly to our POP type equations, but only because
instead of \epsilon_{R, y-1} we would have \epsilon_{R, y-1}. Turns out that's just a
definition difference which is fine.]
- [ ] p44, (A.14) F_{y,a} definition, maybe add 'during year y'.
- [ ] p44, (A.17) Presume that $\log_{2^{0.05}}$ should be $\log_2 0.05$
- [ ] p44, similarly for (A.18), (A.22), (A.23)
- [ ] p45, para 2 - I thought 'apical' was a typo (typical?) but you used it a
lot, so maybe define. I don't think I've ever heard that term!
- [ ] p48, A.5. B^* etc. are commonly used for equilibria, rather than
B^e. Though I think you might be sticking with Tom's notation.

**Comment by andrew-edwards** [comment]
Appendix B
- [ ] p45, last para: modeled -> modelled

Appendix D
- [ ] p68, (D.2). Shouldn't it be
```\sum_{i = y-21}^{y-1}```? Similary for (D.3). Though I think what you have is
correct if $C_i$ is the catch in year $i$ where $i$ goes back in time ($i=1$ is
last year). If so then maybe just clarify the definition here (and that $C_i$ is only
defined that way here; i.e. $C_y$ elsewhere is for true year $y$). Might be
simpler to try my summation suggestion.
- [ ] p69, (D.5) yr -> y

Appendix E
- [ ] p79, para 3 - mention Figure E.2 with E.1 (else figures are not referenced in order)
- [ ] p81, 'centred' -> 'divided' (more specific)? (Should it anyway have been
'centered'?)
- [ ] p85, E.4 point 1 - 'importance' - not quite clear what that means here.
- [ ] p115, I did wonder if you need a conclusion regarding the MPs? Just to tie
it all together (while not actually providing advice).

That's it. Hopefully nothing too major, I think they're all pretty easy, and are just suggestions.

**Comment by robynforrest** [comment]
Thanks for adding these as a GitHub issue Andy!

**Comment by seananderson** [comment]
Thanks @andrew-edwards! Checkboxes and all for that feel-good to-do-list-checking goodness.
