### ISSUE TITLE
May 15 UBC meeting

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#14]
I will be meeting Tom and Quang at UBC on May 15. Please list issues for discussion here.
e.g., Parallel processing, new combos of MPs with HCRs

**Comment by seananderson** [comment]
Brainstorming here:

Biggest issues:
- coming up with an effort timeseries (vessel fleet, depth and locality, species assemblage, positive trips options; hook and line and trawl)
- trawl and hook and line effort -> averaged? encompassed? how to weight? kept separate? cartoonish or precise?
- the big multiple survey and multiple cpue issue with missing years and no overlap
- in general, lots of our data is pretty bad until some year (~1990, ~1996, or ~2007) and then fantastic; strategies for dealing with in CV parameters etc.?
- narrowing down the MPs and simplifying the OMs as much as possible

workflow when current depletion is nearly completely unknown?
   - wide uniform?
   - SP or DD model to get at this, but circular?

Spat_targ - does this come into play with a single area model?

what should we do about observation error if it used to be really big but is now 0? same with Cbiascv
- affects catch and lot of other things because of the history of our fisheries

how should we deal with Iobs and Ibiascv when we have multiple surveys often from different areas and not overlapping (see bigger issues section)

how is Btobs and Btbiascv different from the index slots?

where do things like FMSYbiascv get used? do they apply to any estimate that comes out of an MP before applying HRC?

for things like size at maturity should we be working with females or with both sexes combined?

common causes of warnings like:
Vulnerability (V) is <0.01 for all ages in:
sims:362
years:67

common causes of warnings like:
Note: Maximum age (157) is lower than assuming 1% of cohort survives to maximum age (296)

CV_BMSY_B0, CV_Dt etc. in Data object
   - should these be added or were the MPs tested with these default values (not listed as slots used in documentation)

from your experience, which MPs should we be focused on and which can we easily discard?

strategies for parameterizing similar slots for which we really don't have anything to go on (e.g. observation slots; see github issue)

what can we safely pull out (set to 0 and by default don't mention) to simplify things? see github issue

clarity of code, performance of models, and helper functions built around the TMB models in MSEtool: wow!
