### ISSUE TITLE
Add section describing MSEtool SRA model

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#34]
See vignette. Get Quang to write this.

**Comment by quang-huynh** [comment]
The most recent version of the SRA vignette will be available here and currently can be rendered in an empty environment: https://github.com/tcarruth/MSEtool/blob/master/vignettes/SRA_scope.Rmd

The model was revised last week so that weight and selectivity calculations more closely match those in the operating model.

**Comment by seananderson** [comment]
It looks great, thanks. We may need to integrate the equations and basic model description based on the parameterization we are using into the research document.

**Comment by quang-huynh** [comment]
I just updated the vignette with more emphasis on which OM slots are updated by SRA_scope. For the res doc, some parts of the vignette will not be relevant, e.g. conditioning on effort.
